### ISSUE TITLE
IE section of browsers chart is rendering improperly

### ISSUE THREAD

**Issue by tdlowden** [18F/analytics.usa.gov#765] opened 2021-01-21 15:14 UTC
## What kind of issue?
- [ ] Feature Request?
- [x ] Bug

In the https://analytics.usa.gov/executive-office-president/ and https://analytics.usa.gov/national-aeronautics-space-administration/, the Internet Explorer part of the Browsers chart is rendering as its own separate chart, with "Internet Explorer" in bold, and not representing a total percentage rather than just the % of IE versions. It should be a nested chart within the "Browsers" section.

![image](https://user-images.githubusercontent.com/6556888/105370082-332fdf80-5bd1-11eb-9e50-af558a6d84c8.png)

**Comment by tdlowden** [comment] 2021-01-21 15:15
Thanks to @ryanhofdotgov, we have this info:

Since IE doesn’t exist in the Browser section, this logic doesn’t work. Normally it would render as a sub-chart.

Who would have thought we would live in a world where IE usage falls off the chart?

The offending line of code is really this one:
https://github.com/18F/analytics.usa.gov/blob/92fe548c861a1bf7f309b315bb6d2e1cbb4fa867/js/index.js#L89

Needs to check if the Internet Explorer Key exists in the parent chart before nesting it. Technically also needs to be done with all the other nested charts.

**Comment by ryanwoldatwork** [comment] 2021-01-27 05:29
It appears the the Internet Explorer details are rendered all the time.
After render, the code loops through the browsers listed under "Browsers" and will nest the Internet Explorer element.

However, here, "Internet Explorer" is not showing in the "Browsers" element, so the Internet Explorer element doesn't get nested, as intended.

**Comment by ryanwoldatwork** [comment] 2021-01-27 06:55
Here's a PR https://github.com/18F/analytics.usa.gov/pull/767

The javascript line is perhaps overly cautious, and certainly ugly. But the general take here is to render AND hide the Internet Explorer section by default. And if the Browser section shows an "Internet Explorer" entry, the hidden section will show and be nested.  If an entry for IE does not show, the original section will remain hidden.

**Comment by levinmr** [comment] 2024-08-19 14:04
Closing as the IE sub section of the browsers chart has been removed

**Closed by levinmr** 2024-08-19 14:04 UTC
